config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :all_tasks, only: [:index, :create, :update, :destroy]
  before_action :set_task, only: [:show, :edit, :update, :destroy]


  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    #@task = Task.new(task_params)
    @task  = Task.create(task_params)
  end


  def update
    @task.update(task_params) 
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy

  end

  private

  def all_tasks
    @tasks = Task.all
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:description, :deadline)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task, remote: true do |f|   %>
<div class="form-group">
  <%= f.text_area  :description, placeholder: "Describe your task!", class: "form-control" %>
</div>
<div class="form-group">
  <%= f.text_field :deadline, id: "datetimepicker1", placeholder: "When's it due?", class: "form-control", as: :bootstrap_datepicker %>
</div>
<div class="form-group">
  <%= f.button :submit, class: "btn btn-primary"    %>
</div>
<% end %>

app/views/tasks/_task.html.erb
<li>
  <%= task.description %>
  <%= task.deadline %>
  <%= link_to "Edit", edit_task_path(task), remote: true %>
  <%= link_to "Delete", task, remote: true, method: :delete,
        data: { confirm: 'Are you sure?' } %>
</li>

app/views/tasks/create.js.erb
$('#task-form').html("<%= j ( render 'form' ) %>");
$('#task-form').slideUp(350);
$('#tasks').html("<%= j (render @tasks) %>");

app/views/tasks/destroy.js.erb
$('#tasks').html("<%= j (render @tasks) %>");

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>
<%= render 'datetimepicker' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/edit.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

<%= render 'datetimepicker' %>

app/views/tasks/index.html.erb
<%= link_to 'New Task', new_task_path, remote: true %>

<div id="task-form" style="display:none;"></div>

<h2>Tasks</h2>
<div id="tasks">
  <ul>
    <%= render @tasks %>
  </ul>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>
<%= render 'datetimepicker' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

<%= render 'datetimepicker' %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
$('#tasks').html("<%= j (render 'form') %>");
$('#task-form').slideUp(350);
$('#tasks').html("<%= j (render @tasks) %>");